.github/workflows/publish.yaml
package.json
tools/bump_and_publish_sdks.sh

Add the bump and publish workflow on the `release published` event of Github to automate the release process.
We can then create new release from Github UI, which will trigger a complete CI run + NPM publish of our packages.
The CI workflow was tested on our private legacy repo.

ci: prepare bump and publish from the CI

---

packages/sdks/react/src/lib/useNinetailed.ts

After a recent NX upgrade to latest minor 15.9.7, we noticed a type failing because of a wrong import:
`// from dist folder, generated type`
Removing the type inference and forcing the return type solves the issue:
`// from dist folder, generated type`

fix breaking type for useNinetailed react hook

---

.github/workflows/publish.yaml
tools/bump_and_publish_sdks.sh

using `yarn` seems to use a different registry URL than NPM.
- do not use a yarn command to run the publish script
- printout the npmrc to have more insights on what is used

ci: fix wrong .npmrc config

---

.github/workflows/publish.yaml

On publish workflow, we were missing some rights from the CI to publish with provenance to NPM.
```sh
npm notice Publishing to https://registry.npmjs.org/ with tag beta and public access
npm ERR! code EUSAGE
npm ERR! Provenance generation in GitHub Actions requires "write" access to the "id-token" permission
```

ci: give correct permissions for provenance

---

package.json
packages/plugins/analytics/package.json
packages/plugins/contentsquare/package.json
packages/plugins/google-analytics/package.json
packages/plugins/google-tagmanager/package.json
packages/plugins/insights/package.json
packages/plugins/preview-bridge/package.json
packages/plugins/preview/package.json
packages/plugins/privacy/package.json
packages/plugins/segment/package.json
packages/plugins/ssr/package.json
packages/sdks/gatsby/package.json
packages/sdks/javascript/package.json
packages/sdks/nextjs-esr/package.json
packages/sdks/nextjs/package.json
packages/sdks/nodejs/package.json
packages/sdks/react/package.json
packages/sdks/shared/package.json
packages/utils/contentful/package.json
packages/utils/javascript/package.json
tools/bump_and_publish_sdks.sh

- ci: add `repository` field to all package.json to match with requirements from the NPM provenance flag
- https://docs.npmjs.com/generating-provenance-statements#prerequisites
- https://docs.npmjs.com/cli/v10/configuring-npm/package-json#repository 
- chore: add a check to skip provenance flag when publishing if the repository field is missing from the package.json
- it should prevent the CI failing on future new packages if we forget the set the field
- fix: remove publish:packages from yarn script
- publish should be run without yarn to match the content (registry field) set by node-setup in the CI

Fix release CI by adding a repository field to package.json

---

.verdaccio/config.yml
CONTRIBUTING.md
package.json
packages/playgrounds/next-js/experiences.ts
packages/playgrounds/next-js/pages/_app.tsx
packages/playgrounds/next-js/pages/index.tsx
packages/playgrounds/next-js/pages/index2.tsx
packages/sdks/gatsby/rollup.config.js
project.json
tools/bump_and_publish_sdks.sh
yarn.lock

Add verdaccio as local npm registry.
We can now publish packages locally to verdaccio which acts as a proxy (`nx local-registry` to start it). It enables us to test new packages before releasing them.
Example on how it looks after I ran the publish script with default options `./tools/bump_and_publish_sdks.sh`
NX executor: https://nx.dev/nx-api/js/executors/verdaccio
About Verdaccio: https://verdaccio.org/docs/what-is-verdaccio

Add verdaccio as local npm registry proxy

---

packages/sdks/react/src/lib/Experience/ComponentMarker.tsx
packages/sdks/react/src/lib/Experience/Experience.tsx

For empty variants, that don't render any DOM elements, recursively look up for an element that can be observed.

fix: observe empty variant components

---

packages/sdks/gatsby/gatsby-node.tsx

Using those options results in a warning since they're not part of the `pluginOptionsSchema`.

fix: add missing plugin options in Gatsby schema

---

packages/utils/contentful/src/lib/ExperienceMapper.ts
packages/utils/contentful/src/lib/__test__/ExperienceMapper.spec.ts

The Experience SDK currently only allows for synchronous mapping of variants in the mapCustomExperience  helper method of the Contentful utils SDK.
Some of the SDK users need to do async operations like resolving data from a different system in there already built out data normalization frameworks. They could not reuse their tooling as long as we don’t provide a async helper.
This PR adds a new function `mapCustomExperienceAsync`, which allows to run async operations in the Mapping step of the variant. 
E.g.:
```ts
const mapped = await Promise.all(
EXPERIENCES.map((experience) =>
ExperienceMapper.mapCustomExperienceAsync(
experience,
async (variant) => {
await new Promise((resolve) => setTimeout(resolve, 1000));
return {
id: variant.sys.id,
headline: variant.fields.headline,
};
}
)
)
); …
```

DEV-3694 Add async custom variant mapper to Contentful Utility SDK

---

packages/plugins/google-tagmanager/package.json
packages/plugins/privacy/jest.config.js
packages/plugins/privacy/package.json
packages/plugins/privacy/src/NinetailedPrivacyPlugin.spec.ts
packages/plugins/privacy/src/NinetailedPrivacyPlugin.ts
packages/tests/generated-packages/src/lib/__snapshots__/generated-package-json.spec.ts.snap

This PR adds a second argument to the Privacy Plugin constructor. A privacy config which blocks events, removes traits and properties and also deactivates features, when the consent was given.
___
Enhancement, Tests
___
- Enhanced `NinetailedPrivacyPlugin` to support configurations that apply after consent is given.
- Added comprehensive tests for various configurations and consent scenarios.
- Updated test environment to `jsdom` for better simulation of browser-like environments.
- Added `analytics` as a development dependency to support testing.
___
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Tests
</strong></td><td><table>
<tr>
<td>
<details>
<summary><strong>NinetailedPrivacyPlugin.spec.ts</strong><dd><code>Add comprehensive tests …

DEV-3658 Add option to filter events and deactivate features even if consent is given

---

packages/plugins/preview/project.json
packages/plugins/preview/rollup.config.cjs
packages/sdks/shared/rollup.config.cjs
withPackageVersion.js

The env var `NX_PACKAGE_VERSION` was only replaced in the build step of the shared package.
This PR replaces it properly for the preview plugin
___
Enhancement
___
- Added a new utility function `withPackageVersion` to handle the replacement of the `NX_PACKAGE_VERSION` environment variable in Rollup configurations.
- Updated the Rollup configuration for the preview plugin to use a custom configuration file and integrated the `withPackageVersion` utility.
- Refactored the shared SDK Rollup configuration to use the new `withPackageVersion` utility, removing the inline logic for package version replacement.
___
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Enhancement
</strong></td><td><table>
<tr>
<td>
<details> …

Replace package version env var in all projects

---

packages/utils/contentful/src/types/ExperienceEntry.spec.ts
packages/utils/javascript/src/lib/ExperienceMapper.spec.ts
packages/utils/javascript/src/types/Experiement.spec.ts
packages/utils/javascript/src/types/Experience.spec.ts
packages/utils/javascript/src/types/Experience.ts
packages/utils/javascript/src/types/Experiment.ts

This PR fixes a bug which made it possible to put `variants` as `null` or `undefined` into the `isExperienceEntry` as valid object. As the `variants` didn't get defaulted to an empty array, the `ExperienceMapper.mapExperience` function failed.
___
Bug fix, Tests
___
- Added tests to ensure `null` and invalid variants are not accepted in `ExperienceEntry`.
- Added tests to default missing or null variants to an empty array in `Experiment` and `Experience`.
- Added test to ensure the type of variants is preserved in `ExperienceMapper`.
- Fixed the `parse` and `safeParse` functions in `Experience` and `Experiment` to correctly handle variants.
___
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Tests
</strong></td><td><table>
<tr>
<td> …

Dev 3831 experience js experience mapper wont default a null or missing variants array correctly

---

packages/plugins/insights/src/index.ts

We need this type to use `sendEventBatches()`

chore: export type ComponentViewEventBatch from plugin-insights

---

packages/sdks/javascript/src/lib/Ninetailed.ts
packages/sdks/shared/src/lib/types/SelectedVariantInfo/SelectedVariantInfo.ts

Enhancement
___
- Overwrite the sticky flag in the `experience` object with information from the experience API.
- Update the `SelectedVariantInfo` schema to include a `sticky` property with a default value of `false`.
___
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Enhancement</strong></td><td><table>
<tr>
<td>
<details>
<summary><strong>Ninetailed.ts</strong><dd><code>Overwrite sticky flag with experience API information</code>&nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
packages/sdks/javascript/src/lib/Ninetailed.ts
<li>Added logic to overwrite the sticky flag with information from the <br>experience API.<br> <li> Modified the <code>experience</code> object to include the sticky flag from the <br>selected experience.<br> <li> …

Dev 4259 Use sticky flag from Experience API instead of expericen configuration entry

---

packages/sdks/javascript/src/lib/NinetailedCorePlugin/NinetailedCorePlugin.ts

`abortNonClientEvents` doesn't need to be an instance method. It can exist as a static method on the `NinetailedCorePlugin` because it doesn't access anything on the instance.

fix: turn abortNonClientEvents into a static method

---

packages/plugins/preview/src/lib/plugin/NinetailedPreviewPlugin.ts
packages/plugins/preview/src/lib/plugin/WidgetContainer.ts
packages/sdks/javascript/src/lib/experience/makeExperienceSelectMiddleware.ts
packages/sdks/javascript/src/lib/types/interfaces/HasExperienceSelectionMiddleware.ts

- All preview plugin instances that are not marked as active won't render anything to the DOM and won't listen to any events.  This ensures that at any given time only one instance is active. 
- This change requires a change to the `ExperienceSelectionMiddleware` type by allowing an `undefined` return type because we only want the active preview plugin to return a middleware function.

feat: Limit preview plugin to one instance

---

packages/plugins/insights/package.json
packages/plugins/insights/src/lib/NinetailedInsightsPlugin.ts
packages/sdks/javascript/src/index.ts
packages/sdks/javascript/src/lib/Ninetailed.ts
packages/sdks/javascript/src/lib/guards/requiresEventBuilder.ts
packages/sdks/javascript/src/lib/types/interfaces/RequiresEventBuilder.ts
packages/tests/generated-packages/src/lib/__snapshots__/generated-package-json.spec.ts.snap

Enhancement, Dependencies
___
- Refactored the `NinetailedInsightsPlugin` to use the `EventBuilder` interface for building events.
- Implemented the `RequiresEventBuilder` interface and added error handling for missing `EventBuilder`.
- Exported `RequiresEventBuilder` interface and `EventBuilder` utility in the SDK.
- Added a guard to check if a plugin requires an `EventBuilder` and injected it accordingly.
- Removed the `uuid` dependency from the `insights` package.
___
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Enhancement</strong></td><td><table>
<tr>
<td>
<details>
<summary><strong>NinetailedInsightsPlugin.ts</strong><dd><code>Refactor event building to use EventBuilder interface</code>&nbsp; &nbsp; &nbsp; &nbsp; </dd></summary> …

Dev 4016 Handle the building of events in InsightsPlugin through EventBuilder

---

packages/plugins/insights/src/lib/api/NinetailedInsightsApiClient.ts

Aborting API calls in the [fetchTimeout](https://github.com/ninetailed-inc/experience.js/blob/fa81270d2a7133fcb9888f36c46abbfa4faa3b7b/packages/sdks/shared/src/lib/api/fetch-timeout.ts#L23)  utility function throws an `AbortError` exception. This exception shouldn't be thrown all the way up to caller  and reach external error reporting tools such as Sentry. 
This PR stops the propagation of this exception when sending insights events batches.

fix: stop abort errors from bubbling up for insights API calls

---

packages/plugins/insights/src/lib/NinetailedInsightsPlugin.ts
packages/plugins/preview/src/lib/plugin/NinetailedPreviewPlugin.ts
packages/plugins/ssr/src/lib/analytics/plugin.ts
packages/sdks/javascript/src/lib/types/ProfileChangedPayload.ts

[DEV-4470](https://contentful.atlassian.net/browse/DEV-4470)
The `NinetailedCorePlugin` can dispatch the `PROFILE_CHANGE` event with a null profile. This was not reflected in the type of the event payload, and therefore some component seen events were being sent with a null profile, causing validation errors on the backend. 
[DEV-4470]: https://contentful.atlassian.net/browse/DEV-4470?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: send component view events only when a profile exists

---

packages/plugins/privacy/src/NinetailedPrivacyPlugin.spec.ts
packages/plugins/privacy/src/NinetailedPrivacyPlugin.ts

The Privacy Plugin was ignoring the setting of `allowedTrackEvents: ['*']` and expected every track event name to get listed out. This PR check if `*` is in the list and then allows any event name, no matter which other names are listed.
Potentially, we could change the signature to `string[] | '*'` which makes the typing a bit more explicit.
___
enhancement, tests
___
- Enhanced the `NinetailedPrivacyPlugin` to allow all track events if `allowedTrackEvents` is set to include '*'.
- Updated the default privacy configuration to include '*' in `allowedTrackEvents`.
- Added a test case to ensure that track events are not blocked when '*' is specified in `allowedTrackEvents`.
- Introduced a mock function for `track` in the test plugin to verify the behavior.
___
<table><thead><tr><th></th><th …

Privacy Plugin: Check if allowedTrackEvents is set to * and allow all

---

packages/plugins/preview/src/lib/plugin/NinetailedPreviewPlugin.ts
packages/plugins/preview/src/lib/plugin/WidgetContainer.ts

Related bug ticket with further explanation can be found [here](https://contentful.atlassian.net/browse/DEV-3478).
Preview widget ribbons does not cover the area underneath anymore.

fix: prevent dead spot underneath preview widget ribbon

---

packages/plugins/analytics/.babelrc
packages/plugins/insights/.babelrc

Only the analytics and insights plugins are bundling their polyfills because of their babel configuration.
Before:
After:

fix: stop bundling polyfills

---

packages/sdks/react/src/lib/useFlag.ts
packages/utils/contentful/src/types/__snapshots__/ExperienceEntry.spec.ts.snap
packages/utils/javascript/src/types/Config.ts

- Resolved "Maximum update depth exceeded" warning caused by re-renders from un-memoized defaultValue in the useFlag hook.
- Optimized the useFlag hook to use deep equality checks internally to avoid unnecessary resets and re-renders — even when defaultValue is passed as a fresh object.
- started using preprocessor for the components to make sure any component would have a type field.

Nt 1037 fix preview widget maximum depth bug

---

packages/playgrounds/easy-hr/components/Variable/Variable.tsx
packages/plugins/analytics/src/index.ts
packages/plugins/analytics/src/lib/ElementSeenPayload.ts
packages/plugins/analytics/src/lib/NinetailedAnalyticsPlugin.spec.ts
packages/plugins/analytics/src/lib/NinetailedAnalyticsPlugin.ts
packages/plugins/analytics/src/lib/NinetailedPlugin.ts
packages/plugins/analytics/src/lib/constants.ts
packages/plugins/analytics/test/fixtures.ts
packages/plugins/insights/src/lib/NinetailedInsightsPlugin.spec.ts
packages/plugins/insights/src/lib/NinetailedInsightsPlugin.ts
packages/plugins/segment/src/NinetailedSegmentPlugin.spec.ts
packages/sdks/javascript/src/index.ts
packages/sdks/javascript/src/lib/Ninetailed.spec.ts
packages/sdks/javascript/src/lib/Ninetailed.ts
packages/sdks/javascript/src/lib/NinetailedCorePlugin/NinetailedCorePlugin.ts
packages/sdks/javascript/src/lib/NinetailedCorePlugin/actions.ts
packages/sdks/javascript/src/lib/types/index.ts
packages/sdks/javascript/src/lib/types/interfaces/InterestedInSeenVariables.ts
packages/sdks/javascript/src/lib/utils/EventBuilder.ts
packages/sdks/react/src/lib/Experience/Experience.tsx
packages/sdks/react/src/lib/useFlag.ts
packages/sdks/shared/src/lib/event/build-component-view-event.ts
packages/sdks/shared/src/lib/types/Event/ComponentViewEvent.ts
packages/sdks/shared/src/lib/types/ExperienceDefinition/BaselineWithVariants.ts
packages/tests/javascript-integration/src/lib/analytics-pipeline.spec.ts
packages/tests/javascript-integration/src/lib/multiple-analytics-plugins.spec.ts

What I did in this PR:
- Implement the componentView tracking for custom flags to be sent through the SDK to our insights API.
- Found a minor issue when testing where it was mistakenly stored as `value: { value: {...} }`
- We added the componentType field to differentiate between different componentView events. 
**_Context: we have recently been getting some requests regarding the component tracking for custom flags and this is the PR that implements that._**
Diagram on how we are sending componentView events:

Nt 943 enable sdk to send component view events

---

packages/plugins/preview-bridge/src/PreviewPluginApi.ts
packages/plugins/preview/src/lib/plugin/NinetailedPreviewPlugin.ts

We are deprecating `openExperienceAnalytics` because all the traffic should be directed to the Contentful entries for checking the insights. 
The analytics page that the `openExperienceAnalytics` method navigates to, is no longer active. We will remove this method completely in future releases.

fix: deprecate openExperienceAnalytics

---

packages/plugins/privacy/src/NinetailedPrivacyPlugin.ts

Component view (impression) events were being forwarded to the Insights API **before consent**, even though the Privacy plugin was installed and configured to block them.
This meant that users who had not yet opted-in still generated impression data, which violated the intended privacy gating.
- `component` events appeared in network logs prior to consent being given.
- Privacy plugin logs/handlers sometimes never fired before the first impressions.
- Changing allowlists in the plugin config had no effect intermittently.
- Behavior looked “magical” and was hard to pin down because when we initially introduced this impression blocking features in the privacy plugin it was working, but at some point it stopped.
The bug appeared when we added `loaded()` and `ready()` checks into the Privacy …

Privacy Plugin doesn't prevent componentView events from being fired

---

packages/plugins/preview/package.json
packages/plugins/preview/src/lib/plugin/NinetailedPreviewPlugin.ts

An endless loop occurs in the 9T preview plugin when:
- One content entry references at least two personalized entries
- Both entries use the same personalization experience
- The experience has custom flags with JSON array/object values
- Both entries are rendered on the same page
it only compares references, not deep equality. When two personalized entries use the same experience and flag, but with different object values, the equality check always returns false, causing repeated updates and an endless loop.

fix: improve variable overwrite comparison using isEqual from radash
